#!/usr/bin/env python

import argparse
import json
import os
import subprocess
import sys

def find_compilation_databases(build_path):
    for root, dirs, entries in os.walk(os.path.abspath(build_path)):
        for entry in entries:
            if entry == 'compile_commands.json':
                yield os.path.join(root, entry)

def hacks(command):
    # Remove -DCMAKE_CFG_INTDIR because it requires weird escaping
    for elm in command:
        if elm.startswith('-DCMAKE_CFG_INTDIR'):
            command.remove(elm)

    return command

def create_xargs_file(compilation_database):
    with open(compilation_database) as fp:
        json_data = json.load(fp)

    cxx_flags = os.getenv('DXR_CLANG_FLAGS')
    assert cxx_flags is not None

    xargs_commands = []

    for entry in json_data:
        if '/swift/stdlib/' in entry['file']:
            continue

        command = entry['command'].split()

        o_index = command.index('-o')
        object_file = os.path.join(entry['directory'], command[o_index+1])
        if not os.path.isfile(object_file):
            continue

        # Dump output to /dev/null
        command[o_index+1] = '/dev/null'

        # Replace compiler
        compiler = command[0]
        if compiler.endswith('cc') or compiler.endswith('clang'):
            compiler = 'clang'
        elif compiler.endswith('c++') or compiler.endswith('clang++'):
            compiler = 'clang++'
        command[0] = compiler

        # Preprocess instead of compiling
        c_index = command.index('-c')
        command[c_index] = '-fsyntax-only'

	# Add the C++ flags we want
        command.insert(1, cxx_flags)

	# Stop xargs on failure
	command.extend(['||', 'exit', '255'])

        command = hacks(command)

        xargs_commands.append(' '.join(command))

    root = os.path.dirname(compilation_database)
    xargs_file = os.path.join(root, 'compilation_commands.xargs')
    with open(xargs_file, 'w') as fp:
        fp.write('\n'.join(xargs_commands))

    return xargs_file

def call_xargs(xargs_file):
    os.chdir(os.path.dirname(xargs_file))
    xargs_cmd = [
        'xargs',
        '--arg-file={}'.format(xargs_file),
        '--max-procs=4', '--replace', '--verbose',
        '/bin/sh', '-c', '{}'
    ]
    try:
        subprocess.check_call(xargs_cmd)
    except Exception as exc:
        print(str(exc))

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--build-path", required=True,
                        help="Path to look for compilation databases.")
    args = parser.parse_args()

    # 1 - Find every compilation database in the build directory
    compilation_databases = find_compilation_databases(args.build_path)

    # 2 - Create the file containing the commands we want to pass to xargs(1)
    xargs_files = [
        create_xargs_file(compilation_database)
        for compilation_database in compilation_databases
    ]

    # 3 - Execute each xargs file
    for xargs_file in xargs_files:
        call_xargs(xargs_file)
